<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Akshay" failures="1" tests="4" name="Test" time="11.06" errors="0" timestamp="2024-02-17T12:42:14 IST">
  <testcase classname="DemoShoppingApp.Tests.LoginTests" name="loginTestPositive" time="0.346"/>
  <testcase classname="DemoShoppingApp.Tests.LoginTests" name="loginTest_locked_user" time="0.29">
    <failure type="java.lang.AssertionError" message="expected [Epi sadface: Sorry, this user has been locked out.] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: expected [Epi sadface: Sorry, this user has been locked out.] but found [Epic sadface: Sorry, this user has been locked out.]
at DemoShoppingApp.Tests.LoginTests.loginTest_locked_user(LoginTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginTest_locked_user -->
  <testcase classname="DemoShoppingApp.Tests.LoginTests" name="loginTest_wrongCredentials" time="0.289"/>
  <testcase classname="DemoShoppingApp.Tests.Test2" name="endToEndTesting" time="0.946"/>
</testsuite> <!-- Test -->
